### ISSUE TITLE
Patch error : client and server _etag don't match

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-backend-import#10]
Sometimes, this error occurs when importing `realm` objects in the backend ... see around line 502 in cfg_to_backend.py ...

```
~~~~~~~~~~~~~~~~~~~~~~ post realms ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Late update for: realm/576396be4c988c6bf74377ea -> {'resource': 'realm', 'type': 'simple', '_etag': u'bc0f2e3cddcbc424a0961a894ce2bc993060c183', 'value': 'ea9a05e2b77a4e93bbd862d57167f721'}
Late update for: realm/576396be4c988c6bf74377ea -> {'_parent': u'576396be4c988c6bf74377e9'}
Late update for: realm/576396be4c988c6bf74377e9 -> {'resource': 'realm', 'type': 'simple', '_etag': u'eac9146ff741b270c9f31013cdd2673c40ba10ad', 'value': 'ea9a05e2b77a4e93bbd862d57167f721'}
Late update for: realm/576396be4c988c6bf74377e9 -> {'_parent': u'576396be4c988c6bf74377e9'}
# Patch error for: realm/576396be4c988c6bf74377e9 : {'_parent': u'576396be4c988c6bf74377e9'}
***** Exception: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}
***** Traceback: %s Traceback (most recent call last):
  File "/home/shinken/alignak-backend-import/alignak_backend_import/cfg_to_backend.py", line 520, in update_later
    resp = self.backend.patch(endpoint, data, headers, True)
  File "/home/shinken/alignak-backend-client/alignak_backend_client/client.py", line 538, in patch
    data=data, headers=headers, inception=False
  File "/home/shinken/alignak-backend-client/alignak_backend_client/client.py", line 541, in patch
    raise BackendException(412, response.content, response)
BackendException: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}

***** response: <Response [412]>

```

**Comment by mohierf** [comment]
Indeed _parent attribute is the same as _id ... we try to say that the element is its own parent!
