### ISSUE TITLE
Realm update does not work 

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-backend-import#49]
Alignak-backend-import with "-d" does not work.
Works with "-e", but "-e" does not delete the "Europe" realm.
In this case, the APP login does not work either.
It only helps "drop all mongo database" and the Grafana configuration must then be recreated.

~~~~~~~~~~~~~~~~~~~~~~~~~~
grep -v ^# /usr/local/etc/alignak/arbiter/objects/realms/all.cfg | grep -v ^$

define realm {
    realm_name             All
    default                1
}

alignak-backend-import -d -b http://127.0.0.1:5000 /usr/local/etc/alignak/alignak.cfg

Elapsed time after Arbiter has loaded the configuration: 0.66206407547
~~~~~~~~~~~~~~~~~~~~~~~~~~~ Backend authentication ~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Authenticated ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elapsed time after templates are built: 0.859951972961
~~~~~~~~~~~~~~~~~~~~~~~~ Deleting existing backend data ~~~~~~~~~~~~~~~~~~~~~~
Deleting realms
 -> deleting realm: Europe
# Backend deletion error
***** Exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 409 Client Error: CONFLICT for url: http://127.0.0.1:5000/realm/5869edf8f8f9b86ac4b5f572
***** Traceback: %s Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 452, in delete_data
    self.backend.delete('realm/' + element['_id'], headers)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 680, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 409 Client Error: CONFLICT for url: http://127.0.0.1:5000/realm/5869edf8f8f9b86ac4b5f572

***** response: None
'~~~~~~~~~~~~~~~~~~~~~~~~~~'
Exiting with error code: 5


#In this case, the APP login does not work either

[2017-01-02 07:53:46,899]> alignak_backend_client.client : [ERROR] Backend connection error, error: HTTPConnectionPool(host='192.168.1.1', port=5000): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000558C5C0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
[2017-01-02 07:53:46,900]> alignak_app.widgets.login : [ERROR] Bad credentials in login form ! Missing password !
[2017-01-02 07:53:46,900]> alignak_app.widgets.login : [ERROR] Backend error code 1000: Backend connection error

**Comment by mohierf** [comment]
@spea1: I tried several times and I did not get any errors ... should you try it again please?

**Comment by mohierf** [comment]
This problem is fixed since a while ... the backend import script deletes the realms from the lowest level to the upper one to avoid deleting parents before children.
