### ISSUE TITLE
Update problem only changed "host_name"

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-backend-import#52]
```

Update problem, I have only changed "host_name"
# -----------------------------------------------------------------------------
# alignak-backend-import -e -b http://127.0.0.1:5000 /usr/local/etc/alignak/alignak.cfg
# -----------------------------------------------------------------------------


...................................
Manage resource service: 7cc160b46ef94091b45766bcdc2624b6 (generic_passive_service)
- new command check_command: d088fe7efd1a4ce593c5d150c28005b7 - _echo - []
 --> service, realm: 42ad921ed5f44b0db02b515228b3213e
Service host/description: W2012R2-NSCA/generic_passive_service
*** Object not found for host
Set item 'tags' as: [u'generic-passive-service']
 --> id_name: service_description
 --> replaced name for service: generic_passive_service
Updating service: generic_passive_service
Traceback (most recent call last):
  File "/usr/local/bin/alignak-backend-import", line 11, in <module>
    load_entry_point('alignak-backend-import==0.6.7', 'console_scripts', 'alignak-backend-import')()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 2382, in main
    fill = CfgToBackend()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 385, in __init__
    self.import_objects()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 2215, in import_objects
    self.manage_resource('service', data_later, 'service_description', schema)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 1789, in manage_resource
    'host': item['host']
KeyError: 'host'

# -----------------------------------------------------------------------------
# alignak-backend-import -d -b http://127.0.0.1:5000 /usr/local/etc/alignak/alignak.cfg
# -----------------------------------------------------------------------------

 -> deleting service: Disk /tmp
ERROR:alignak_backend_client.client:Backend HTTP error, error: 412 Client Error: PRECONDITION FAILED for url: http://127.0.0.1:5000/service/586e7272f8f9b83b3b18ba0f
# Backend deletion error
***** Exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 412 Client Error: PRECONDITION FAILED for url: http://127.0.0.1:5000/service/586e7272f8f9b83b3b18ba0f
***** Traceback: %s Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 555, in delete_data
    self.backend.delete('service/' + element['_id'], headers)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client-0.5.2-py2.7.egg/alignak_backend_client/client.py", line 687, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 412 Client Error: PRECONDITION FAILED for url: http://127.0.0.1:5000/service/586e7272f8f9b83b3b18ba0f

***** response: None
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 5



# -----------------------------------------------------------------------------
# alignak-backend-import -e -b http://127.0.0.1:5000 /usr/local/etc/alignak/alignak.cfg
# -----------------------------------------------------------------------------
...................................
Manage resource service: 7596c249787442f8b8dd8f098f9f1a13 (Windows-Event-Log)
- new command check_command: 4cadeaad762249d8a49e1372b419a7eb - check_nrpe - [u'alias_event_log']
-> Added check_command_args: [u'alias_event_log']
 --> service, realm: cd187ce3f9f84106ac220dda02493049
 --> Windows-Event-Log, servicegroups: ['64a0d91549fe44d6bd427e271363aeb8']
Service host/description: Win8-NRPE/Windows-Event-Log
*** Object not found for host
*** Object list not found for service_dependencies
Set item 'tags' as: [u'windows-nrpe-service']
 --> id_name: service_description
 --> replaced name for service: Windows-Event-Log
Updating service: Windows-Event-Log
Traceback (most recent call last):
  File "/usr/local/bin/alignak-backend-import", line 11, in <module>
    load_entry_point('alignak-backend-import==0.6.7', 'console_scripts', 'alignak-backend-import')()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 2382, in main
    fill = CfgToBackend()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 385, in __init__
    self.import_objects()
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 2215, in import_objects
    self.manage_resource('service', data_later, 'service_description', schema)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_import-0.6.7-py2.7.egg/alignak_backend_import/cfg_to_backend.py", line 1789, in manage_resource
    'host': item['host']
KeyError: 'host'

# -----------------------------------------------------------------------------
# alignak-backend-import -d -b http://127.0.0.1:5000 /usr/local/etc/alignak/alignak.cfg
 # -----------------------------------------------------------------------------
 
 ~~~~~~~~~~~~~~~~~~~~~~ add serviceescalations ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elapsed time after importation: 13.838310957
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alignak_backend_import, inserted elements:
 - 71 command(s)
 - 48 host(s)
 - 2 hostdependency(s)
 - no hostescalation(s)
 - 13 hostgroup(s)
 - 1 realm(s)
 - 66 service(s)
 - 21 servicedependency(s)
 - no serviceescalation(s)
 - 11 servicegroup(s)
 - 4 timeperiod(s)
 - 3 user(s)
 - 2 usergroup(s)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Global configuration import duration: 13.8394720554

```

**Comment by mohierf** [comment]
I will not try to fix this ... probalby that I will remove the update feature, since we now have the `alignak-backend-cli` shipped with the alignak backend python client: https://github.com/Alignak-monitoring-contrib/alignak-backend-client
