### ISSUE TITLE
"alignak-backend-import==0.7.0" import not work eg. import alignak-demo

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-backend-import#57]
```
pip freeze | grep alignak
alignak==0.2
alignak-backend==0.7.2
alignak-backend-client==0.5.2
alignak-backend-import==0.7.0
alignak-checks-monitoring==0.3.0
alignak-checks-mysql==0.3.0
alignak-checks-nrpe==0.3.3
alignak-checks-snmp==0.3.5
alignak-checks-wmi==0.3.0
alignak-demo==0.1.9
alignak-module-backend==0.3.3
alignak-module-external-commands==0.3.0
alignak-module-logs==0.3.3
alignak-module-nsca==0.3.1
alignak-module-ws==0.3.1
alignak-notifications==0.3.0

alignak-backend-import -d -m /usr/local/etc/alignak/alignak.cfg
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alignak_backend_import, version: 0.7.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command line parsing error.
alignak_backend_import -h will display the command line parameters syntax.
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 64


alignak_backend_import -d -b http://127.0.0.1:5000 /usr/local/etc/alignak-pre-demo/alignak.cfg
Traceback (most recent call last):
  File "/usr/local/bin/alignak_backend_import", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 677, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'alignak-backend-import==0.5.3rc0' distribution was not found and is required by the application

pip uninstall alignak-backend-import==0.7.0
cd /tmp
git clone https://github.com/Alignak-monitoring-contrib/alignak-backend-import.git
cd alignak-backend-import
sudo pip install --upgrade -r requirements.txt
sudo python setup.py install
pip freeze | grep alignak-backend-import
alignak-backend-import==0.6.10

~~~~~~~~~~~~~~~~~~~~~~ add serviceescalations ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elapsed time after importation: 20.2875430584
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alignak_backend_import, inserted elements:
 - 77 command(s)
 - 13 host(s)
 - 27 host_template(s)
 - 1 hostdependency(s)
 - no hostescalation(s)
 - 10 hostgroup(s)
 - 3 realm(s)
 - 240 service(s)
 - 149 service_template(s)
 - 149 servicedependency(s)
 - no serviceescalation(s)
 - 8 servicegroup(s)
 - 5 timeperiod(s)
 - 5 user(s)
 - 4 usergroup(s)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Global configuration import duration: 20.2894089222


```

**Comment by mohierf** [comment]
The most recent `alignak-backend-import` do not use anymore the `-m` option to specify that templates must be imported. They are always imported if they exist in the configuration
