### ISSUE TITLE
Indentation error on cfg_to_backend.py ?

### ISSUE THREAD

**Issue by BastienMarais** [Alignak-monitoring-contrib/alignak-backend-import#83]
Hi ! 
When I wanted to import my contacts.cfg file I had a notificationway problem that blocked everything. But i haven't mentioned notificationway on my file ==> why i have this error ?

## We can see on line 1678 of cfg_to_backend.py :   

```python
 if 'notificationways' in item:
                    # Make commands a unique list
                    item['host_notification_commands'] = \
                        list(set(item['host_notification_commands']))
                    item['service_notification_commands'] = \
                        list(set(item['service_notification_commands']))

                    self.output("  User host notification commands: %s"
                                % item['host_notification_commands'])
                    self.output("  User service notification commands: %s"
                                % item['service_notification_commands'])
item.pop('notificationways')   ### This is line 1678
``` 

 ## I just change indentation :  

```python
 if 'notificationways' in item:
                    # Make commands a unique list
                    item['host_notification_commands'] = \
                        list(set(item['host_notification_commands']))
                    item['service_notification_commands'] = \
                        list(set(item['service_notification_commands']))

                    self.output("  User host notification commands: %s"
                                % item['host_notification_commands'])
                    self.output("  User service notification commands: %s"
                                % item['service_notification_commands'])
                    item.pop('notificationways')   ### This is line 1678
``` 
And it's good i can import my contacts.cfg

It's realy an indentation error or just i am lucky :p ?

**Comment by mohierf** [comment]
Not sure it is the correct fix. I am curious to see what was your error. Please would you copy the console output ?

**Comment by BastienMarais** [comment]
I can't give you the console output for à moment but i can the 13/10/17. The error was i think :
Element 'notificationway' not found on item.pop('notificationway') line 1678 of cfg_to_backend.py

**Comment by flaf** [comment]
Hi,

@BastienMarais, maybe @mohierf could be interested by your gist [here](https://gist.github.com/BastienMarais/afcf3b60a4cbb9379ed14068b8bce992). ;)

**Comment by BastienMarais** [comment]
Hi @flaf !
You're right, but after I made a file with all my commands, timeperiods and contacts which led to another error that I paste in a file.txt on my work computer.

**Comment by BastienMarais** [comment]
Hi @mohierf ! This is the console output.

**Actions :**
Regroup all commands,timeperiods and contacts in one file.cfg .
Import this file.

**Result :**
```
Traceback (most recent call last):
  File "/usr/local/bin/alignak-backend-import", line 11, in <module>
    load_entry_point('alignak-backend-import==1.0.0', 'console_scripts', 'alignak-backend-import')()
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_import/cfg_to_backend.py", line 2638, in main
    fill = CfgToBackend()
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_import/cfg_to_backend.py", line 364, in __init__
    self.import_objects()
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_import/cfg_to_backend.py", line 2137, in import_objects
    self.manage_resource('user', data_later, 'name', schema, template=True)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_import/cfg_to_backend.py", line 1678, in manage_resource
    item.pop('notificationways')
KeyError: 'notificationways'
```
**FIX :**
Change the indentation in line 1678 of  : 
/usr/local/lib/python2.7/site-packages/alignak_backend_import/cfg_to_backend.py

**Comment by mohierf** [comment]
I reproduced the problem and I will submit a fix (yours ;)...). Thanks
